codecov:
  branch: 1.x

coverage:
  status:
    patch: false
    project:
      default:
        target: 80
        branches:
          - 1.x

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default