codecov:
  branch: 1.x

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 80
        branches: 1.x

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
